language: node_js
node_js:
- '8'
install:
- npm i -g metricly-cli
script:
- metricly package validate && metricly package lint
notifications:
  slack:
    secure: CGcDRQo5pQaIj+9V2M8Sw7wkEs0dk0nPFZyZllC/dxgxuzrxrO5jve9sywFsOwvxya8WAbzsKwP7Xse9OTdpp5vNsC/NLzjCfMEsojLhdKNQygcc7dWoDSToe9Kpf8O8YyOqFa+YbceghIoVBHrNiT41pJAhlVkui10MTv4HRRpSZi0N5JBgxjfkhE+7so/JHUxqprHG9j4Ow/2Pe0gioO5BSWXkrMb2DGyJEO29Yzh7FWwOGxiQHS7VtOcMdyeIX7QkRHcjc5VuidCd7BiuJGXsemkBqe0a/3CbGRbi4KMoMslRg2vaj6co/QPieOPvIRrEgLUF63LRc7lE3gyEt6vEKF/kuaZALlbgraChTOCWqNCbGWlLwQ0ABccC80hKkmZdlW5I6bm1L4dtL0VXg+cU/bfMJ8ilr9TouKQS4YRpDoCznKmilWq5suK6EcU0WHhCobdPum1IexUqO4E1bt/YDwSTim7na7IZTqk7OlbRC9Ght5ZQxigMKFAYsEYezKfLQt7Cg0F3VWEDwTYZR20mrf5n2CLpHfpMHLlwwmdCMK7L9r3ir70aVIBhrHJOwAIz6RGy5KDsx6WivhPIiMMZaFIIdanOhJg+2GpoC/ZrI1p7JYkUmoh193vRlAz8WP4e0ASx8tn9/PHffDdbx3iPdGqhUvGZUfSloJTuDQM=
